id: P009495
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 19:41:22.472940
source_metadata:
  id: bdr:W00KG07624
  title: བཅོས་དཀའི་ནད་ཀྱི་གཉེན་པོའི་སྨན་སྦྱོར་གཅེས་བཏུས
  author: ''
  volumes:
    2fe0fdb8e53a4be197557421499127aa:
      image_group_id: I00KG07863
      title: ''
      volume_number: 1
      total_pages: 140
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
