id: P009495
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG07624
  title: བཅོས་དཀའི་ནད་ཀྱི་གཉེན་པོའི་སྨན་སྦྱོར་གཅེས་བཏུས
  author: ''
  volumes:
    2fe0fdb8e53a4be197557421499127aa:
      image_group_id: I00KG07863
      title: ''
      volume_number: 1
      total_pages: 140
